## 유저정보
CREATE TABLE MEMBER_INFO(
NAME VARCHAR(30) NOT NULL,
ID VARCHAR(30) PRIMARY KEY,
PW VARCHAR(30) NOT NULL
);

## 게시판
CREATE TABLE STOREGE(
S_INDEX INT AUTO_INCREMENT PRIMARY KEY,
DATE DATE NOT NULL,
TITLE VARCHAR(100) NOT NULL,
CONTENT VARCHAR(3000) NOT NULL,
ID VARCHAR(30) NOT NULL,
CLICK INT DEFAULT 0 NOT NULL,
CONSTRAINT M_F_G01 FOREIGN KEY STOREGE(ID) REFERENCES MEMBER_INFO(ID)
);

## 댓글
CREATE TABLE COMENT(
C_INDEX INT AUTO_INCREMENT PRIMARY KEY,
ID VARCHAR(30) NOT NULL,
STOREGE_ID INT NOT NULL,
COMENTS VARCHAR(1000),
CONSTRAINT M_F_G02 FOREIGN KEY COMENT(ID) REFERENCES MEMBER_INFO(ID),
CONSTRAINT M_F_G04 FOREIGN KEY COMENT(STOREGE_ID) REFERENCES STOREGE(S_INDEX)
);

## 감정박스
CREATE TABLE EMOTION(
E_INDEX INT AUTO_INCREMENT PRIMARY KEY,
DATE DATE NOT NULL,
ID VARCHAR(30) NOT NULL,
TEXT VARCHAR(3000) NOT NULL,
EMOTIONS VARCHAR(10) NOT NULL,
CONSTRAINT M_F_G03 FOREIGN KEY EMOTION(ID) REFERENCES MEMBER_INFO(ID)
);


# 테스트
INSERT INTO MEMBER_INFO
VALUES ('1','1','1');

INSERT INTO STOREGE(DATE,TITLE,CONTENT,ID)
VALUE (now(),'1','1','1');

INSERT INTO COMENT(ID,COMENTS)
VALUES ('1','1');

INSERT INTO EMOTION(DATE,ID,TEXT,EMOTIONS)
VALUES (now(),'1','안녕하세요','중립');

SELECT * FROM EMOTION
# 내 아이디로 작성한 타이틀
SELECT S.DATE,S.ID, S.TITLE
FROM MEMBER_INFO M, STOREGE S
WHERE M.ID = S.ID;

# 댓글 확인 
SELECT S.TITLE, C.COMENTS
FROM MEMBER_INFO M, COMENT C,STOREGE S
WHERE M.ID = C.ID AND M.ID = S.ID;

-- 채팅 테스트
CREATE TABLE CHATTING(
C_INDEX INT AUTO_INCREMENT PRIMARY KEY,
DATE DATETIME NOT NULL,
TO_ID VARCHAR(30) NOT NULL,
FROM_ID VARCHAR(30) NOT NULL,
CHAT VARCHAR(3000) NOT NULL
)
-- to : 보내는 사람 from : 받는 사람
INSERT INTO CHATTING(DATE,TO_ID,FROM_ID,CHAT)
VALUES (now(),'김수민','김수지','나는 수민');
INSERT INTO CHATTING(DATE,TO_ID,FROM_ID,CHAT)
VALUES (now(),'김수민','김수지','안녕하세요');
INSERT INTO CHATTING(DATE,TO_ID,FROM_ID,CHAT)
VALUES (now(),'1','김수지','안녕하세요');
INSERT INTO CHATTING(DATE,TO_ID,FROM_ID,CHAT)
VALUES (now(),'김수민','1','안녕하세요');


# 테스트
SELECT TO_ID, DATE_FORMAT(DATE,'%y-%m-%d %H:%i') AS DATE, FROM_ID,CHAT
FROM CHATTING
WHERE TO_ID ='김수민'
ORDER BY DATE DESC;


# TO_ID 중복제거
SELECT DISTINCT TO_ID 
FROM CHATTING
WHERE FROM_ID = '김수지'







DROP TABLE CHATTING


## EMOTION 확인
SELECT @rownum:=@rownum+1 as rownum, E.*
FROM (SELECT * FROM EMOTION WHERE ID='1' AND (@rownum :=0)=0 ORDER BY DATE DESC) E


